name: palemoon # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '28.5.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Pale Moon web browser; forked from Firefox # 79 char long summary
description: |
  Pale Moon is an Open Source, Goanna-based web browser available for Microsoft Windows and Linux (with other operating systems in development), focusing on efficiency and customization. Make sure to get the most out of your browser!

  Pale Moon offers you a browsing experience in a browser completely built from its own, independently developed source that has been forked off from Firefox/Mozilla code a number of years ago, with carefully selected features and optimizations to improve the browser's stability and user experience, while offering full customization and a growing collection of extensions and themes to make the browser truly your own.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

layout:
  /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
  /etc/fonts:
    bind: $SNAP/etc/fonts

parts:
  palemoon:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://linux.palemoon.org/datastore/release/palemoon-$SNAPCRAFT_PROJECT_VERSION.linux-x86_64.tar.bz2
    build-packages: [libfreetype6,libpng16-16,libfontconfig1,libxrender1,libasound2,libdbus-glib-1-2,libgtk2.0-0,libx11-xcb1,libxt6,libstdc++-8-dev]
    stage-packages: [libfreetype6,libpng16-16,libfontconfig1,libxrender1,libasound2,libdbus-glib-1-2,libgtk2.0-0,libx11-xcb1,libxt6,unity-gtk2-module,ttf-ubuntu-font-family,libgdk-pixbuf2.0-0,libglib2.0-bin,locales-all,xdg-user-dirs,dmz-cursor-theme,gnome-themes-standard,shared-mime-info,hicolor-icon-theme,xdg-desktop-portal-kde,xdg-desktop-portal-gtk]

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/gtk2
    default-provider: gtk-common-themes:gtk-2-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes

apps:
  palemoon:
    command: palemoon %U
    plugs:
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11
      - browser-support
