name: palemoon # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '28.6.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Pale Moon web browser; forked from Firefox # 79 char long summary
description: |
   Pale Moon is an Open Source, Goanna-based web browser that offers you a browsing experience in a browser completely built from its own, independently developed source that has been forked off from Firefox/Mozilla code a number of years ago, with carefully selected features and optimizations to improve the browser's stability and user experience, while offering full customization and a growing collection of extensions and themes to make the browser truly your own.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  palemoon:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://linux.palemoon.org/datastore/release/palemoon-$SNAPCRAFT_PROJECT_VERSION.linux-x86_64.tar.bz2
    #build-packages:
      #- build-essential
      #- libgtk2.0-dev
      #- libdbus-glib-1-dev
      #- autoconf2.13
      #- yasm
      #- libegl1-mesa-dev
      #- libasound2-dev
      #- libxt-dev
      #- zlib1g-dev
      #- libssl-dev
      #- libsqlite3-dev
      #- libbz2-dev
      #- libpulse-dev
      #- zip
      #- python2.7
      #- python-dbus
      #- libstdc++-8-dev
    stage-packages: [libfreetype6,libpng16-16,libfontconfig1,libxrender1,libasound2,libdbus-glib-1-2,libgtk2.0-0,libx11-xcb1,libxt6,unity-gtk2-module,ttf-ubuntu-font-family,libgdk-pixbuf2.0-0,libglib2.0-bin,locales-all]

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-2-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes

apps:
  palemoon:
    command: palemoon
    plugs:
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11
      - browser-support
      - gtk-2-engines
      - gtk-2-themes
      - sound-themes
      - icon-themes
    environment:
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
